// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoNZsMzHjaqvNWa1HjMxeISn3Mksx6ZIo',
    appId: '1:63417815638:web:40cdfb1dc7eca04ae861f7',
    messagingSenderId: '63417815638',
    projectId: 'team-it-e6c00',
    authDomain: 'team-it-e6c00.firebaseapp.com',
    storageBucket: 'team-it-e6c00.appspot.com',
    measurementId: 'G-TTDP197B9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnta9an-MGC_-UQ21g2sa6Pq7YhpzaBL4',
    appId: '1:63417815638:android:c6a6ea773f45ad02e861f7',
    messagingSenderId: '63417815638',
    projectId: 'team-it-e6c00',
    storageBucket: 'team-it-e6c00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbBSHZ13_N47FzvZMOzbBKj77LsQYgO3A',
    appId: '1:63417815638:ios:8a35c375dae3d6a7e861f7',
    messagingSenderId: '63417815638',
    projectId: 'team-it-e6c00',
    storageBucket: 'team-it-e6c00.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbBSHZ13_N47FzvZMOzbBKj77LsQYgO3A',
    appId: '1:63417815638:ios:5e03eeb3f56dba71e861f7',
    messagingSenderId: '63417815638',
    projectId: 'team-it-e6c00',
    storageBucket: 'team-it-e6c00.appspot.com',
    iosBundleId: 'com.example.untitled2.RunnerTests',
  );
}
